defaults:
  - base
  - _self_

tokenizer:
  pretrained_model_name_or_path: lightblue/suzume-llama-3-8B-japanese
model:
  pretrained_model_name_or_path: lightblue/suzume-llama-3-8B-japanese
dataset:
  path: json
prompt:
  template: ja/train_suzume_llama3_8b.jinja2
trainer:
  dataset_text_field: null
training_args:
  num_train_epochs: 10  # エポック数
  per_device_train_batch_size: 8  # 学習バッチサイズ
  per_device_eval_batch_size: 8  # 評価バッチサイズ
