GPUS:
  - [ '0', '1', '2', '3' ]
  - [ '4', '5', '6', '7' ]
GPU_MEMORY_UTILIZATION: 0.9
LITELLM_PORT: 4000
MODELS:
  - <path to mdk>/outputs/trainer/yyyy-mm-dd/hh-MM-ss/checkpoint-x-merged
  - tokyotech-llm/Swallow-70b-instruct-hf
MODEL_NAMES:
  - llmjp-x-merged
  - tokyotech-llm/Swallow-70b-instruct-hf
NUM_WORKERS: 8
OPEN_WEBUI_PORT: 3000
TEMPLATES:
  - ../../../templates/ja/launcher_llmjp3.jinja2
  - ../../../templates/ja/launcher_chatml.jinja2
WEBUI_AUTH: False
